package dev.setup.miniApps;

import biology.descriptor.VKPred;
import biology.protein.ChainFactory;
import biology.protein.ProteinChain;
import modules.descriptor.vkbat.control.PRABI_VK;
import utilities.LocalToolBase;

/**
 * Times PRABI Algorithms
 * @author Benjy Strauss
 *
 */

public class PRABI_Timer extends LocalToolBase {
	
	private static final VKPred[] ALGORITHMS = { VKPred.GOR1, VKPred.GOR3, VKPred.GOR4, VKPred.DPM,
			VKPred.PREDATOR_PR, VKPred.HNN, VKPred.MLRC, VKPred.PHD, VKPred.DSC,
			VKPred.SOPM, VKPred.SOPMA, VKPred.SIMPA96
	};
	
	private static final ProteinChain[] SEQUENCES = {
			ChainFactory.makeRCSB("4JJX", "A", "SNAMNSQLTLRALERGDLRFIHNLNNNRNIMSYWFEEPYESFDELEELYNKHIHDNAERRFVVEDAQKNLIGLVELIEINYIHRSAEFQIIIAPEHQGKGFARTLINRALDYSFTILNLHKIYLHVAVENPKAVHLYEECGFVEEGHLVEEFFINGRYQDVKRMYILQSKYLNRSE"),
			ChainFactory.makeRCSB("5BTR", "A", "GSRDNLLFGDEIITNGFHSCESDEEDRASHASSSDWTPRPRIGPYTFVQQHLMIGTDPRTILKDLLPETIPPPELDDMTLWQIVINILSEPPKRKKRKDINTIEDAVKLLQESKKIIVLTGAGVSVSSGIPDFRSRDGIYARLAVDFPDLPDPQAMFDIEYFRKDPRPFFKFAKEIYPGQFQPSLCHKFIALSDKEGKLLRNYTQNIDTLEQVAGIQRIIQCHGSFATASCLICKYKVDCEAVRGDIFNQVVPRCPRCPADEPLAIMKPEIVFFGENLPEQFHRAMKYDKDEVDLLIVIGSSLKVRPVALIPSSIPHEVPQILINREPLPHLHFDVELLGDCDVIINELCHRLGGEYAKLSSNPVKLSEITEQYLFLPPNRYIFHGAEVYSDSEDDV"),
			ChainFactory.makeRCSB("3QB8", "A", "MYTLIKLTSEYTSRAISFTSRNFVASEPTSIALKLTTCDFTTSFQNIMKQCVDYGHSFAFVDADDNIKAQILNIPYDAYENMHYGNIRETDPMFDLFGNLDSYTPDDKCLYVFAIGSEVTGKGLATKLLKKTIEESSSHGFKYIYGDCTNIISQNMFEKHGFETVGSVKYKGYQYGITKPFDSINCTEYIKRMVKTI"),
			ChainFactory.makeRCSB("4HNY", "A", "MSRKRSTKPKPAAKIALKKENDQFLEALKLYEGKQYKKSLKLLDAILKKDGSHVDSLALKGLDLYSVGEKDDAASYVANAIRKIEGASASPICCHVLGIYMRNTKEYKESIKWFTAALNNGSTNKQIYRDLATLQSQIGDFKNALVSRKKYWEAFLGYRANWTSLAVAQDVNGERQQAINTLSQFEKLAEGKISDSEKYEHSECLMYKNDIMYKAASDNQDKLQNVLKHLNDIEPCVFDKFGLLERKATIYMKLGQLKDASIVYRTLIKRNPDNFKYYKLLEVSLGIQGDNKLKKALYGKLEQFYPRCEPPKFIPLTFLQDKEELSKKLREYVLPQLERGVPATFSNVKPLYQRRKSKVSPLLEKIVLDYLSGLDPTQDPIPFIWTNYYLSQHFLFLKDFPKAQEYIDAALDHTPTLVEFYILKARILKHLGLMDTAAGILEEGRQLDLQDRFINCKTVKYFLRANNIDKAVEVASLFTKNDDSVNGIKDLHLVEASWFIVEQAEAYYRLYLDRKKKLDDLASLKKEVESDKSEQIANDIKENQWLVRKYKGLALKRFNAIPKFYKQFEDDQLDFHSYCMRKGTPRAYLEMLEWGKALYTKPMYVRAMKEASKLYFQMHDDRLKRKSDSLDENSDEIQNNGQNSSSQKKKAKKEAAAMNKRKETEAKSVAAYPSDQDNDVFGEKLIETSTPMEDFATEFYNNYSMQVREDERDYILDFEFNYRIGKLALCFASLNKFAKRFGTTSGLFGSMAIVLLHATRNDTPFDPILKKVVTKSLEKEYSENFPLNEISNNSFDWLNFYQEKFGKNDINGLLFLYRYRDDVPIGSSNLKEMIISSLSPLEPHSQNEILQYYLYPYDVPDYA"),
			ChainFactory.makeRCSB("4AVA", "A", "MDGIAELTGARVEDLAGMDVFQGCPAEGLVSLAASVQPLRAAAGQVLLRQGEPAVSFLLISSGSAEVSHVGDDGVAIIARALPGMIVGEIALLRDSPRSATVTTIEPLTGWTGGRGAFATMVHIPGVGERLLRTARQRLAAFVSPIPVRLADGTQLMLRPVLPGDRERTVHGHIQFSGETLYRRFMSARVPSPALMHYLSEVDYVDHFVWVVTDGSDPVADARFVRDETDPTVAEIAFTVADAYQGRGIGSFLIGALSVAARVDGVERFAARMLSDNVPMRTIMDRYGAVWQREDVGVITTMIDVPGPGELSLGREMVDQINRVARQVIEAVG")
	};
	
	// [algorithm][sequence #]
	private static double[][] times = new double[ALGORITHMS.length][SEQUENCES.length];
	
	public static void main(String[] args) throws Exception {
		
		for(int index = 0; index < SEQUENCES.length; ++index) {
			for(int index2 = 0; index2 < ALGORITHMS.length; ++index2) {
				long time = System.currentTimeMillis();
				
				String val = PRABI_VK.getPRABIServer(SEQUENCES[index], ALGORITHMS[index2]);
				qp(val);
				
				times[index2][index] = System.currentTimeMillis() - time;
			}
		}
		
		for(int index = 0; index < SEQUENCES.length; ++index) {
			for(int index2 = 0; index2 < ALGORITHMS.length; ++index2) {
				qp(SEQUENCES[index].id() + ": " + ALGORITHMS[index2] + ":\t\t\t" + times[index2][index]);
			}
		}
	}

}
